### ISSUE TITLE
It looks ugly

### ISSUE THREAD

**Issue by NoobAndProud-01** [digimezzo/knowte-electron#93]
First, thank you to the dev.
What attracted me Knowte 1 was its beautiful UI, Kwnote 2 is Meh. What happened?
Also Right click is disabled.
Screenshot: https://imgur.com/a/UsRKOkm

**Comment by digimezzo** [comment]
@NoobAndProud-01 Thank you for your feedback. I'm sorry to see that you don't like the new design. It is the result of a complete rewrite using a different framework (in order to make it cross platform). The idea was to add more Material design elements. The menu design was also influenced by confusion that some users had about the main menu (note, settings, information) being below the submenu (ALL, TODAY, ...).

I do agree, however, seeing both designs side by side and, especially, with this choice of accent color, that the version 1 design is much more vibrant. The version 2 design looks somewhat washed out and more classic. So I'd like to improve that for version 2.0.1, and go back to a design the closely resembles version 1.

Please keep and eye on this issue. I'll post back here (with pictures) when I've reworked the design. Your feedback is valued.

**Comment by digimezzo** [comment]
I've already changed the design to resemble version 1 more. This is still work in progress:

![image](https://user-images.githubusercontent.com/11945339/69005778-1cd02900-0927-11ea-8034-6cefd89c8816.png)

**Comment by digimezzo** [comment]
Knowte 2.0.1 beta 1 improves the design. I'm closing this issue.

**Comment by NoobAndProud-01** [comment]
Forgot about this one. Thank you!
